--
-- PostgreSQL database dump
--

\restrict l0Hj2mXgnkrJ72PoJD5zZwzg3KM8lZhVskHvWLhO5WX5JJgocZwM5Tl64JdAzZr

-- Dumped from database version 15.16 (Debian 15.16-1.pgdg13+1)
-- Dumped by pg_dump version 17.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: copy_operations_to_user_answers(integer); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.copy_operations_to_user_answers(p_user_id integer) RETURNS void
    LANGUAGE plpgsql
    AS $$
BEGIN
  INSERT INTO user_answers (user_id, operation_id)
  SELECT p_user_id, p4.f4_index
  FROM user_process_1_access a
  JOIN process_1 p1 ON p1.f1_index = a.f1_index
  JOIN process_2 p2 ON p2.f1_index = p1.f1_index
  JOIN process_3 p3 ON p3.f2_index = p2.f2_index
  JOIN process_4 p4 ON p4.f3_index = p3.f3_index
  WHERE a.user_id = p_user_id
    AND p4.is_active IS DISTINCT FROM false;
END;
$$;


ALTER FUNCTION public.copy_operations_to_user_answers(p_user_id integer) OWNER TO postgres;

--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


ALTER FUNCTION public.set_updated_at() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: executors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.executors (
    id smallint NOT NULL,
    name text,
    note text
);


ALTER TABLE public.executors OWNER TO postgres;

--
-- Name: process_1; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.process_1 (
    f1_index text NOT NULL,
    f1_name text NOT NULL,
    note text,
    is_active boolean DEFAULT true,
    sort smallint
);


ALTER TABLE public.process_1 OWNER TO postgres;

--
-- Name: process_2; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.process_2 (
    f2_index text NOT NULL,
    f1_index text,
    f2_name text,
    sort bigint,
    note text,
    is_active boolean
);


ALTER TABLE public.process_2 OWNER TO postgres;

--
-- Name: process_3; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.process_3 (
    f3_index text NOT NULL,
    f2_index text,
    f3_name text,
    sort bigint,
    note text,
    is_active boolean
);


ALTER TABLE public.process_3 OWNER TO postgres;

--
-- Name: process_4; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.process_4 (
    f4_index text NOT NULL,
    f3_index text,
    f4_name text,
    sort bigint,
    note text,
    is_active boolean DEFAULT true,
    executor_id integer
);


ALTER TABLE public.process_4 OWNER TO postgres;

--
-- Name: systems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.systems (
    system_id integer NOT NULL,
    system_name text NOT NULL,
    is_active boolean DEFAULT true
);


ALTER TABLE public.systems OWNER TO postgres;

--
-- Name: systems_system_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.systems ALTER COLUMN system_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.systems_system_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_answers (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    operation_id text NOT NULL,
    labor_hours numeric(10,2),
    system_id integer,
    note text,
    is_done boolean DEFAULT false,
    done_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.user_answers OWNER TO postgres;

--
-- Name: user_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_process_1_access; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_process_1_access (
    user_id integer NOT NULL,
    f1_index text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.user_process_1_access OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    username text NOT NULL,
    password_hash text NOT NULL,
    full_name text,
    role text DEFAULT 'respondent'::text NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: executors executors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.executors
    ADD CONSTRAINT executors_pkey PRIMARY KEY (id);


--
-- Name: process_1 process_1_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.process_1
    ADD CONSTRAINT process_1_pkey PRIMARY KEY (f1_index);


--
-- Name: process_2 process_2_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.process_2
    ADD CONSTRAINT process_2_pkey PRIMARY KEY (f2_index);


--
-- Name: process_3 process_3_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.process_3
    ADD CONSTRAINT process_3_pkey PRIMARY KEY (f3_index);


--
-- Name: process_4 process_4_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.process_4
    ADD CONSTRAINT process_4_pkey PRIMARY KEY (f4_index);


--
-- Name: systems systems_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.systems
    ADD CONSTRAINT systems_pkey PRIMARY KEY (system_id);


--
-- Name: systems systems_system_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.systems
    ADD CONSTRAINT systems_system_name_key UNIQUE (system_name);


--
-- Name: user_answers user_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_answers
    ADD CONSTRAINT user_answers_pkey PRIMARY KEY (id);


--
-- Name: user_answers user_answers_user_id_operation_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_answers
    ADD CONSTRAINT user_answers_user_id_operation_id_key UNIQUE (user_id, operation_id);


--
-- Name: user_process_1_access user_process_1_access_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_process_1_access
    ADD CONSTRAINT user_process_1_access_pkey PRIMARY KEY (user_id, f1_index);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: user_answers_operation_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_answers_operation_id_idx ON public.user_answers USING btree (operation_id);


--
-- Name: user_answers_user_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_answers_user_id_idx ON public.user_answers USING btree (user_id);


--
-- Name: user_answers trg_user_answers_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_user_answers_updated_at BEFORE UPDATE ON public.user_answers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- Name: process_2 process_2_f1_index_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.process_2
    ADD CONSTRAINT process_2_f1_index_fkey FOREIGN KEY (f1_index) REFERENCES public.process_1(f1_index);


--
-- Name: process_3 process_3_f2_index_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.process_3
    ADD CONSTRAINT process_3_f2_index_fkey FOREIGN KEY (f2_index) REFERENCES public.process_2(f2_index);


--
-- Name: process_4 process_4_executor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.process_4
    ADD CONSTRAINT process_4_executor_id_fkey FOREIGN KEY (executor_id) REFERENCES public.executors(id) ON DELETE SET NULL;


--
-- Name: process_4 process_4_f3_index_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.process_4
    ADD CONSTRAINT process_4_f3_index_fkey FOREIGN KEY (f3_index) REFERENCES public.process_3(f3_index);


--
-- Name: user_answers user_answers_operation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_answers
    ADD CONSTRAINT user_answers_operation_id_fkey FOREIGN KEY (operation_id) REFERENCES public.process_4(f4_index);


--
-- Name: user_answers user_answers_system_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_answers
    ADD CONSTRAINT user_answers_system_id_fkey FOREIGN KEY (system_id) REFERENCES public.systems(system_id);


--
-- Name: user_answers user_answers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_answers
    ADD CONSTRAINT user_answers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_process_1_access user_process_1_access_f1_index_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_process_1_access
    ADD CONSTRAINT user_process_1_access_f1_index_fkey FOREIGN KEY (f1_index) REFERENCES public.process_1(f1_index) ON DELETE CASCADE;


--
-- Name: user_process_1_access user_process_1_access_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_process_1_access
    ADD CONSTRAINT user_process_1_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict l0Hj2mXgnkrJ72PoJD5zZwzg3KM8lZhVskHvWLhO5WX5JJgocZwM5Tl64JdAzZr

