import pg from 'pg';
import fs from 'fs';

async function run() {
    const pool = new pg.Pool({
        connectionString: 'postgresql://postgres:postgres@127.0.0.1:5433/refdb'
    });

    const client = await pool.connect();
    console.log('[refdb] Подключено к эталонной базе. Запуск миграции f*_index -> id...');

    try {
        await client.query('BEGIN');

        await client.query(`
            DO $$
            BEGIN
                -- 1. Drop dependent tables to allow FK changes
                DROP TABLE IF EXISTS user_answers CASCADE;
                DROP TABLE IF EXISTS user_process_1_access CASCADE;

                -- 2. Drop old FK constraints and old PKs
                ALTER TABLE process_4 DROP CONSTRAINT IF EXISTS process_4_f3_index_fkey;
                ALTER TABLE process_3 DROP CONSTRAINT IF EXISTS process_3_f2_index_fkey;
                ALTER TABLE process_2 DROP CONSTRAINT IF EXISTS process_2_f1_index_fkey;
                ALTER TABLE process_4 DROP CONSTRAINT IF EXISTS process_4_pkey CASCADE;
                ALTER TABLE process_3 DROP CONSTRAINT IF EXISTS process_3_pkey CASCADE;
                ALTER TABLE process_2 DROP CONSTRAINT IF EXISTS process_2_pkey CASCADE;
                ALTER TABLE process_1 DROP CONSTRAINT IF EXISTS process_1_pkey CASCADE;

                -- 3. Add integer id as new primary key, and new FK columns
                ALTER TABLE process_1 ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
                ALTER TABLE process_2 ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
                ALTER TABLE process_3 ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;
                ALTER TABLE process_4 ADD COLUMN IF NOT EXISTS id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

                ALTER TABLE process_1 ALTER COLUMN f1_index DROP NOT NULL;
                ALTER TABLE process_2 ALTER COLUMN f2_index DROP NOT NULL;
                ALTER TABLE process_3 ALTER COLUMN f3_index DROP NOT NULL;
                ALTER TABLE process_4 ALTER COLUMN f4_index DROP NOT NULL;

                ALTER TABLE process_2 ADD COLUMN IF NOT EXISTS process_1_id integer;
                ALTER TABLE process_3 ADD COLUMN IF NOT EXISTS process_2_id integer;
                ALTER TABLE process_4 ADD COLUMN IF NOT EXISTS process_3_id integer;

                -- 4. Populate new FK columns from old string indexes
                UPDATE process_2 p2 SET process_1_id = p1.id FROM process_1 p1 WHERE p2.f1_index = p1.f1_index AND p2.process_1_id IS NULL;
                UPDATE process_3 p3 SET process_2_id = p2.id FROM process_2 p2 WHERE p3.f2_index = p2.f2_index AND p3.process_2_id IS NULL;
                UPDATE process_4 p4 SET process_3_id = p3.id FROM process_3 p3 WHERE p4.f3_index = p3.f3_index AND p4.process_3_id IS NULL;

                -- 5. Add FK constraints on new integer columns
                ALTER TABLE process_2 DROP CONSTRAINT IF EXISTS process_2_process_1_id_fkey;
                ALTER TABLE process_2 ADD CONSTRAINT process_2_process_1_id_fkey FOREIGN KEY (process_1_id) REFERENCES process_1(id) ON DELETE CASCADE;
                
                ALTER TABLE process_3 DROP CONSTRAINT IF EXISTS process_3_process_2_id_fkey;
                ALTER TABLE process_3 ADD CONSTRAINT process_3_process_2_id_fkey FOREIGN KEY (process_2_id) REFERENCES process_2(id) ON DELETE CASCADE;
                
                ALTER TABLE process_4 DROP CONSTRAINT IF EXISTS process_4_process_3_id_fkey;
                ALTER TABLE process_4 ADD CONSTRAINT process_4_process_3_id_fkey FOREIGN KEY (process_3_id) REFERENCES process_3(id) ON DELETE CASCADE;

                -- 6. Now safely DROP the old string indexes since we don't need them anymore!
                ALTER TABLE process_1 DROP COLUMN IF EXISTS f1_index CASCADE;
                ALTER TABLE process_2 DROP COLUMN IF EXISTS f2_index CASCADE;
                ALTER TABLE process_2 DROP COLUMN IF EXISTS f1_index CASCADE;
                ALTER TABLE process_3 DROP COLUMN IF EXISTS f3_index CASCADE;
                ALTER TABLE process_3 DROP COLUMN IF EXISTS f2_index CASCADE;
                ALTER TABLE process_4 DROP COLUMN IF EXISTS f4_index CASCADE;
                ALTER TABLE process_4 DROP COLUMN IF EXISTS f3_index CASCADE;

            END $$;
        `);

        await client.query('COMMIT');
        console.log('[refdb] Миграция успешно применена. Старые текстовые ключи удалены.');
    } catch (err) {
        await client.query('ROLLBACK');
        console.error('[refdb] Ошибка миграции:', err);
    } finally {
        client.release();
        await pool.end();
    }
}

run();
