-- Core reference tables (structure matches the remote DB)
CREATE TABLE IF NOT EXISTS process_1 (
  id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  f1_name   text NOT NULL,
  note      text,
  is_active boolean NOT NULL DEFAULT true,
  sort      integer
);

CREATE TABLE IF NOT EXISTS process_2 (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_1_id integer REFERENCES process_1(id) ON DELETE CASCADE,
  f2_name      text NOT NULL,
  sort         integer,
  note         text,
  is_active    boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS process_3 (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_2_id integer REFERENCES process_2(id) ON DELETE CASCADE,
  f3_name      text NOT NULL,
  sort         integer,
  note         text,
  is_active    boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS executors (
  id   integer PRIMARY KEY,
  name text NOT NULL,
  note text
);

CREATE TABLE IF NOT EXISTS process_4 (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  process_3_id integer REFERENCES process_3(id) ON DELETE CASCADE,
  f4_name      text NOT NULL,
  sort         integer,
  note         text,
  is_active    boolean NOT NULL DEFAULT true,
  executor_id  integer REFERENCES executors(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS systems (
  system_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_name text NOT NULL UNIQUE,
  is_active   boolean NOT NULL DEFAULT true
);

-- App tables
CREATE TABLE IF NOT EXISTS users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  full_name     text,
  role          text NOT NULL DEFAULT 'respondent',
  is_active     boolean DEFAULT true,
  created_at    timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_process_1_access (
  user_id      integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  process_1_id integer NOT NULL REFERENCES process_1(id) ON DELETE CASCADE,
  created_at   timestamptz DEFAULT now(),
  PRIMARY KEY (user_id, process_1_id)
);

CREATE TABLE IF NOT EXISTS user_answers (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  process_4_id  integer NOT NULL REFERENCES process_4(id) ON DELETE CASCADE,
  labor_hours   numeric(10,2),
  system_id     integer REFERENCES systems(system_id),
  note          text,
  is_done       boolean DEFAULT false,
  done_at       timestamptz,
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now(),
  UNIQUE (user_id, process_4_id)
);

CREATE TABLE IF NOT EXISTS user_added_operations (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  process_3_id  integer NOT NULL REFERENCES process_3(id) ON DELETE CASCADE,
  name          text NOT NULL,
  labor_hours   numeric(10,2),
  system_id     integer REFERENCES systems(system_id) ON DELETE SET NULL,
  note          text,
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS user_answers_user_id_idx ON user_answers(user_id);
CREATE INDEX IF NOT EXISTS user_answers_process_4_id_idx ON user_answers(process_4_id);
CREATE INDEX IF NOT EXISTS user_added_operations_user_id_idx ON user_added_operations(user_id);
CREATE INDEX IF NOT EXISTS user_added_operations_process_3_id_idx ON user_added_operations(process_3_id);

CREATE INDEX IF NOT EXISTS process_2_process_1_id_idx ON process_2(process_1_id);
CREATE INDEX IF NOT EXISTS process_3_process_2_id_idx ON process_3(process_2_id);
CREATE INDEX IF NOT EXISTS process_4_process_3_id_idx ON process_4(process_3_id);
CREATE INDEX IF NOT EXISTS process_4_executor_id_idx ON process_4(executor_id);
CREATE INDEX IF NOT EXISTS user_process_1_access_process_1_id_idx ON user_process_1_access(process_1_id);

-- Copy operations to user answers based on access to process_1
CREATE OR REPLACE FUNCTION copy_operations_to_user_answers(p_user_id integer)
RETURNS void AS $$
BEGIN
  INSERT INTO user_answers (user_id, process_4_id)
  SELECT p_user_id, p4.id
  FROM user_process_1_access a
  JOIN process_1 p1 ON p1.id = a.process_1_id
  JOIN process_2 p2 ON p2.process_1_id = p1.id
  JOIN process_3 p3 ON p3.process_2_id = p2.id
  JOIN process_4 p4 ON p4.process_3_id = p3.id
  WHERE a.user_id = p_user_id
    AND p4.is_active IS DISTINCT FROM false
  ON CONFLICT DO NOTHING;
END;
$$ LANGUAGE plpgsql;

-- updated_at helper
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_user_answers_updated_at ON user_answers;
CREATE TRIGGER trg_user_answers_updated_at
BEFORE UPDATE ON user_answers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_user_added_operations_updated_at ON user_added_operations;
CREATE TRIGGER trg_user_added_operations_updated_at
BEFORE UPDATE ON user_added_operations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
