-- Core reference tables (structure matches the remote DB)
CREATE TABLE IF NOT EXISTS process_1 (
  f1_index  text PRIMARY KEY,
  f1_name   text NOT NULL,
  note      text,
  is_active boolean DEFAULT true,
  sort      smallint
);

CREATE TABLE IF NOT EXISTS process_2 (
  f2_index  text PRIMARY KEY,
  f1_index  text REFERENCES process_1(f1_index),
  f2_name   text,
  sort      bigint,
  note      text,
  is_active boolean
);

CREATE TABLE IF NOT EXISTS process_3 (
  f3_index  text PRIMARY KEY,
  f2_index  text REFERENCES process_2(f2_index),
  f3_name   text,
  sort      bigint,
  note      text,
  is_active boolean
);

CREATE TABLE IF NOT EXISTS executors (
  id   smallint PRIMARY KEY,
  name text,
  note text
);

CREATE TABLE IF NOT EXISTS process_4 (
  f4_index    text PRIMARY KEY,
  f3_index    text REFERENCES process_3(f3_index),
  f4_name     text,
  sort        bigint,
  note        text,
  is_active   boolean DEFAULT true,
  executor_id integer REFERENCES executors(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS systems (
  system_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  system_name text NOT NULL UNIQUE,
  is_active   boolean DEFAULT true
);

-- App tables
CREATE TABLE IF NOT EXISTS users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  full_name     text,
  role          text NOT NULL DEFAULT 'respondent',
  is_active     boolean DEFAULT true,
  created_at    timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_process_1_access (
  user_id  integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  f1_index text NOT NULL REFERENCES process_1(f1_index) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  PRIMARY KEY (user_id, f1_index)
);

CREATE TABLE IF NOT EXISTS user_answers (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  operation_id  text NOT NULL REFERENCES process_4(f4_index),
  labor_hours   numeric(10,2),
  system_id     integer REFERENCES systems(system_id),
  note          text,
  is_done       boolean DEFAULT false,
  done_at       timestamptz,
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now(),
  UNIQUE (user_id, operation_id)
);

CREATE INDEX IF NOT EXISTS user_answers_user_id_idx ON user_answers(user_id);
CREATE INDEX IF NOT EXISTS user_answers_operation_id_idx ON user_answers(operation_id);

-- Copy operations to user answers based on access to process_1
CREATE OR REPLACE FUNCTION copy_operations_to_user_answers(p_user_id integer)
RETURNS void AS $$
BEGIN
  INSERT INTO user_answers (user_id, operation_id)
  SELECT p_user_id, p4.f4_index
  FROM user_process_1_access a
  JOIN process_1 p1 ON p1.f1_index = a.f1_index
  JOIN process_2 p2 ON p2.f1_index = p1.f1_index
  JOIN process_3 p3 ON p3.f2_index = p2.f2_index
  JOIN process_4 p4 ON p4.f3_index = p3.f3_index
  WHERE a.user_id = p_user_id
    AND p4.is_active IS DISTINCT FROM false;
END;
$$ LANGUAGE plpgsql;

-- updated_at helper
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_user_answers_updated_at ON user_answers;
CREATE TRIGGER trg_user_answers_updated_at
BEFORE UPDATE ON user_answers
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
